Ignore third party files added in the release.
helm/chart-releaser pull request #235
Opened 2022-11-22 14:52 UTC by jvanz

Update the function used to update the index to ignore any file that does not have the chart asset file extension (.tgz). This is necessary because chart-release fails with users add another kind of files in chart release.

Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

2022-11-25 15:32 UTC, unguiculus requested changes

2022-11-25 15:32 UTC, unguiculus commented on pkg/releaser/releaser.go
> +var chartAssetFileExtension = ".tgz"
Should be a `const`.
```suggestion
const chartAssetFileExtension = ".tgz"
```

2022-11-29 12:55 UTC, cpanato approved these changes

2022-11-29 13:14 UTC, cpanato commented
@jvanz please fix the lints and push it again, also can you squash all commits? thanks

2022-11-29 13:18 UTC, jvanz commented
@davidkarlsen, thanks for the quick fix.

2022-11-29 13:35 UTC, jvanz commented
@unguiculus I think we need your approval to move forward. :

2022-11-29 13:40 UTC, cpanato approved these changes

2022-11-29 13:44 UTC, davidkarlsen approved these changes
lgtm, thanks

2022-11-29 13:45 UTC, merged

2022-11-29 13:45 UTC, jvanz commented
:partying_face:

2022-11-29 13:49 UTC, jvanz commented
@cpanato , @unguiculus , @davidkarlsen  is it possible to release a new version of the chart-releaser? Thus, I can update the github action to has this fix as well.

2022-11-29 13:50 UTC, cpanato commented
i will chck other prs this week and we can release in the end of the week

2022-11-29 13:50 UTC, jvanz commented
Great, thanks!

2022-12-09 14:54 UTC, cpanato commented
need a bit more time 😓