enable contributions from forks
helm/chart-releaser pull request #440
Opened 2024-07-30 22:34 UTC by qrkourier

These are the modifications I needed to run Actions so I could send a pull request.

2024-08-08 19:42 UTC, qrkourier commented
@mattclegg Would you take a look at this one, please? I could not get the CI working in my fork with your changes, but the additional changes in this branch did work for me.

2024-08-12 15:24 UTC, mattclegg commented on .github/workflows/release.yaml
> +        if: github.repository_owner == 'helm'
Nice.

2024-08-12 15:25 UTC, mattclegg approved these changes
I can't confirm for the changes to [magefile.go](https://github.com/helm/chart-releaser/pull/440/files#diff-520109d035a196d29d0a86e9c4e6c98e98abf056141b84df68c0d48167b87b25) but the yml changes are correct.

@cpanato Are you able to check this please?

2024-08-22 18:00 UTC, qrkourier commented
@mattclegg Would you please allow the checks to run?

@cpanato Please let me know if I can assist with further testing of explanations.

2024-09-18 07:34 UTC, mattclegg commented
LGTM but I don't have permission for the checks to run as I'm not a maintainer.

2024-09-25 21:10 UTC, qrkourier commented
@cpanato Would you like more explanation, examples, or testing for this?

2024-09-26 11:49 UTC, cpanato commented on .github/workflows/release.yaml
> +        if: github.repository_owner == 'helm'
```suggestion
        if: github.repository == 'helm/chart-releaser'
```

2024-09-26 11:50 UTC, cpanato commented on magefile.go
> +	if os.Getenv("GITHUB_REPOSITORY_OWNER") != "helm" {
i would check for the entire things `helm/chart-releaser`

2024-09-26 11:50 UTC, cpanato requested changes
lgtm

just a few nits

2024-09-26 14:26 UTC, cpanato approved these changes

2024-09-26 14:26 UTC, cpanato commented
thanks

2024-09-26 14:26 UTC, merged