Construct pushURL from remote instead of hardcoding github.com
helm/chart-releaser pull request #94
Opened 2020-11-20 18:03 UTC by rdpa

2020-11-20 18:04 UTC, rdpa commented
closes #91

2021-02-17 18:43 UTC, unguiculus requested changes
Sorry, this slipped through.

2021-02-17 18:43 UTC, unguiculus commented on pkg/git/git.go
> +	pushURLArray := strings.SplitAfter(strings.TrimSpace(string(pushURL)), "https://")
This probably won't work for SSH URLs. Please add a test that verifies the functionality for both, SSH and HTTPS URLs.

2021-02-17 19:07 UTC, rdpa commented
Thanks for the review @unguiculus. I will pick this back up soon. FWIW, the original functionality did not work with SSH either, but regardless it would be good to support, and I should add tests.

2021-02-18 07:48 UTC, unguiculus commented on pkg/git/git.go
> +	pushURLArray := strings.SplitAfter(strings.TrimSpace(string(pushURL)), "https://")
You're right regarding SSH. That's not supported and a token is needed for pushing. chart-releaser is usually used with GitHub Actions which don't use SSH anyways.

2021-03-26 09:05 UTC, afritzler commented
Any updates on this one? Having the same issue here.

2021-04-01 00:05 UTC, rdpa commented
@unguiculus tests added

2021-04-08 13:48 UTC, cpanato approved these changes
lgtm this change, dont see big issue

2021-04-21 19:26 UTC, unguiculus approved these changes

2021-04-21 19:26 UTC, merged