Update releaser to regenerate generated field on index update
helm/chart-releaser pull request #99
Opened 2021-01-14 06:15 UTC by Niksko

Currently, the only time the `generated` field is ever written is when we invoke the repo.NewIndexFile() field. This means that contrary to what you would expect, the `generated` field is not updated when the index is updated.

This adds a single line change that calls `time.Now()` after we have determined that the index is to be updated, and updates the `generated` field before the index is written.

Closes #90

2021-01-14 09:07 UTC, cpanato commented on pkg/releaser/testdata/empty-repo/index.yaml
> +generated: "2019-03-29T22:50:44.751503+01:00"
nit: new line

2021-01-14 09:08 UTC, cpanato requested changes
can you squash the commit as well?

thanks for the fix

2021-01-15 12:13 UTC, cpanato approved these changes
/lgtm

thanks!

2021-02-07 22:56 UTC, Niksko commented
Bump @unguiculus

2021-02-08 13:34 UTC, unguiculus approved these changes

2021-02-08 13:34 UTC, merged

2021-02-14 14:36 UTC, onedr0p commented
Any chance the maintainers here can do a release, are we waiting on something else before that happens?

2021-02-14 14:42 UTC, cpanato commented
@onedr0p I will check that next week

2021-02-14 14:44 UTC, onedr0p commented
Awesome and I just noticed someone created an issue for this, apologies for asking here.

https://github.com/helm/chart-releaser/issues/103